### PR TITLE
added syntax highlighting for code blocks

### PR DESCRIPTION
**Pull request by ghost**
related to #2

### CODE REVIEW

**Comment by ghost** [comment]
Jekyll already supports syntax highlighting according to different languages: https://stackoverflow.com/a/9366913

I copy-pasted css from this answer: https://stackoverflow.com/a/27397299

The preview is available here: https://staging.bots.delta.chat/19/development.html

Unfortunately the mobile view still needs some overflow-x magic.

**Comment by ghost** [comment]
The mobile view needs even more work I think, because this branch is based on master, and not on mobile-css. We need to merge #16 before I can continue working on this, I think.

**Comment by ghost** [comment]
Okay, now that #16 is merged, I rebased on master. Let's see how this looks like now.

**Comment by ghost** [comment]
I think it looks great :) see https://staging.bots.delta.chat/19/development.html

**Review by pabzm — APPROVED** [review]
🆒👍

**Pull request merged**
