### PR TITLE
colorful background

### LINKED ISSUE #2: Beautify pages
These pages should stay simple and clear, but they still need some love. E.g. the header, the link color, maybe the menu.

- [x] mobile-optimized #16 
- [x] code blocks
- [x] link color
- [x] syntax highlighting for code blocks #19 
- [ ] colors!
- [x] bulma redesign #27

### PR DESCRIPTION
**Pull request by ghost**
So, this should be enough to closes #2 :) Hope you like it.

### CODE REVIEW

**Comment by ghost** [comment]
The preview is here: https://staging.bots.delta.chat/22/

Unfortunately at https://staging.bots.delta.chat/22/contact.html the white box is longer than expected. I didn't find out why yet, does anyone have a hint? Anyway, it's not a blocker imo.

Note that the preview doesn't work in my chromium, I think because chromium cashed my referer as staging.bots.delta.chat/19/ o.0 anyway, it's pulling the css from a wrong URL and gets a 404. If you have the same problem, open the page in an anonymous window or in firefox, then it works. :woman_facepalming:

**Comment by pabzm** [comment]
Um, I'm not a fan of color gradients, to be honest.

Me asking for more colours was rather targeting text-and logo-colors, together with a general overhaul of font-selection, layout proportions, etc. Not being more colourful for the sake of it.

Sorry I wasn't clearer before!

Can we somehow put this aside until someone tackles the overall aesthetics of the pages?

**Comment by ghost** [comment]
Yes, we can put that aside :D aesthetics are hard.

**Comment by pabzm** [comment]
Thanks for understanding! :)

**Pull request closed without merging**
