### PR TITLE
Stick menu to the top on mobile

### PR DESCRIPTION
**Pull request by ghost**
In order to approach #2, I made some changes which make the page acceptable on mobile devices.

### CODE REVIEW

**Comment by ghost** [comment]
You can compare it to bots.delta.chat here: https://staging.bots.delta.chat/16/

**Comment by pabzm** [comment]
Thanks!

Can you somehow integrate the "text logo" ("Delta Chat bots") as well? With the current change, all pages but the starting page don't have a immediately visitble hin on the DeltaChat context, besides the image logo (I guess, they are not available at the staging thing).

**Review by pabzm — CHANGES_REQUESTED** [review]
That's better, thanks! But now it has the same font-size and alignment as the menu-links, is only set apart by the color. I think it should be visibly different, e.g. by bigger font-size.

Also: what are the capitalization guidelines, and why is that change included in this PR? I don't see any connection to its topic.

**Comment by ghost** [comment]
The capitalization guidelines are here: http://www.grammarunderground.com/capitalization-of-headlines.html

I just added this quickly. Do you want it in a different PR? I don't think it hurts if it's in here.

**Comment by pabzm** [comment]
The capitalization doesn't really hurt, no. Still I'd like to stick to one topic per PR. Next time please post another PR.

(Smaller PRs can often be merged faster — in a separate PR this commit would already be online :)

**Comment by ghost** [comment]
Yeah, I took the capitalization out for now.

**Review by pabzm — APPROVED** [review]
Thanks! 👍

**Pull request merged**
